### PR TITLE
optimize stuff

### PR DESCRIPTION
**Pull request by mariiaan**

### CODE REVIEW

**Comment by ToyB-Chan** [comment]
I don't think its a good idea to leave the threads hanging like that

**Comment by mariiaan** [comment]
it good

**Comment by ToyB-Chan** [comment]
why?

**Comment by mariiaan** [comment]
we can save memory by not saving the thread pointers

**Comment by mariiaan** [comment]
we need every byte

**Comment by ToyB-Chan** [comment]
oh that's a fair point.
this program is already very memory intensive so its good to cut memory where we can.

**Comment by mariiaan** [comment]
yeah

**Comment by mariiaan** [comment]
maybe we can also utilize the GPU to store more bytes

**Comment by mariiaan** [comment]
alsoo, use the hard drive for more memory

**Pull request merged**
